name: Jason Bobango BSW
favicon: null
layout_spectrum: 0.9213394476100802
typography_spectrum: 0.6964413982350379
title: Personal Success Training and Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8213132657110691
  lightness: 0.3085037819109857
  saturation: 0.5205781564582139
  rhythmicContrast: 0.9411991508677602
purpose: []
